- name: Install common basic packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ basic_packages.common }}"
  become: yes

- name: Install basic packages for Ubuntu/Debian
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ basic_packages.ubuntu }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install basic packages for Fedora/CentOS
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ basic_packages.fedora }}"
  become: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- name: Install common development packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ development_packages.common }}"
  become: yes

- name: Install common network packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ network_packages.common }}"
  become: yes

- name: Install development packages for Ubuntu/Debian
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ development_packages.ubuntu }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Install network packages for Ubuntu/Debian
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ network_packages.ubuntu }}"
  become: yes
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"


    
- name: Install network packages for Fedora/CentOS
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ network_packages.fedora }}"
  become: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"

- name: Install development packages for Fedora/CentOS
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ development_packages.fedora }}"
  become: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Fedora"



