- name: Install very basic packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ basic_packages }}"
  become: yes


- name: Install development packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ development_packages }}"
  become: yes

- name: Install network packages
  package:
      name: "{{ item }}"
      state: present
  with_items: "{{ network_packages }}"
  become: yes


